CREATE SEQUENCE IF NOT EXISTS SEQ_TEST_TABLE_TABLE;
CREATE TABLE TEST_RECORD (
  ID          INT DEFAULT (NEXT VALUE FOR SEQ_TEST_TABLE_TABLE) PRIMARY KEY NOT NULL,
  DEP_CODE    VARCHAR(20)                                                   NOT NULL,
  DEP_JOB     VARCHAR(100)                                                  NOT NULL,
  DESCRIPTION VARCHAR(100),
  CONSTRAINT NATURAL_KEY UNIQUE (DEP_CODE, DEP_JOB)
);

INSERT INTO TEST_RECORD(DEP_CODE,DEP_JOB,DESCRIPTION) VALUES ('001', 'ADMIN', 'MAN');
INSERT INTO TEST_RECORD(DEP_CODE,DEP_JOB,DESCRIPTION) VALUES ('002', 'PROGRAMMER', 'MAN');

